Algoritmo "03"
// Descrição   : Cálculo da Soma e média de dois números
// Autor(a)    : Pinto Filipe
// Data atual  : 24/04/2021
Var
// Seção de Declarações das variáveis 
   nota1, nota2, media: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Informe a primeira nota: ")
   Leia(nota1)
   Escreva("Informe a segunda nota: ")
   Leia(nota2)
   media <- (nota1 + nota2)/2
   Escreval("A média de ",nota1, " e", nota2, " é ", media)
Fimalgoritmo
