Algoritmo "05"
// Descrição   : Algoritmo de Cálculo do dobro de um número
// Autor(a)    : Pinto Filipe
// Data atual  : 24/04/2021
Var
// Seção de Declarações das variáveis 
   numero, dobro: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Informe um numero: ")
   Leia(numero)
   dobro <- numero * 2
   Escreval("O dobro de ", numero, " é ", dobro)
Fimalgoritmo
