Algoritmo "09"
// Descrição   : Algoritmo de reconhecimento se número é par ou impar
// Autor(a)    : Pinto Filipe
// Data atual  : 24/04/2021
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe um número: ")
   leia(numero)
   
   se numero % 2 = 0 entao
      escreva(numero, " é um numero par")
   senao
      escreva(numero, " é um numero ímpar")
   fimse


Fimalgoritmo
