Algoritmo "16"
// Descrição   : Algoritmo de contagem de número, terminando no valor digitado
// Autor(a)    : Pinto Filipe
// Data atual  : 24/04/2021
Var
   // Seção de Declarações das variáveis
   i, numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Informe o término da Contagem:")
   leia(numero)
   escreva("Contagem:")
   para i<- 0 ate numero faca
      escreval(i, ", ")
   fimpara
   escreva("FIM!")



Fimalgoritmo
