algoritmo "17"
// Função :  algoritmo que leia a idade de uma pessoal.Determine quantos dias aproximadamente esta pessoa já viveu.
//Escreva o nome da pessoa e o número de dias vividos-
// Autor(a)    : Pinto Filipe
// Data atual  : 24/04/2021

// Seção de Declarações
var
       anos:inteiro
       dias:real
inicio
// Seção de Comandos 
escreva ("Informe a idade em anos: ")
leia (anos)
dias <- (anos * 365.25)
escreva ("Dias vividos: ", dias:4:0)
fimalgoritmo
