Algoritmo "19"
// Descrição   : Algoritmo de multiplicação de um número dado.
// Autor(a)    : Pinto Filipe
// Data atual  : 24/04/2021
Var
   // Seção de Declarações das variáveis
   numero, i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Informe um número: ")
   leia(numero)
   para i <- 1 ate 12 faca
      escreval(numero, " x", i, " =", numero*i)
   fimpara


Fimalgoritmo
